// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxkbfyuethvifurzqpwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4a2JmeXVldGh2aWZ1cnpxcHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzQ0NzMsImV4cCI6MjA2NTE1MDQ3M30.os7N6zKGrYzbdbqS8A5yxz7Uef8bCXodYR7mr90HGOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);